Update setup script to reflect new map libraries

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,88 +1,137 @@
 #!/bin/bash
 set -eu
 
-profile="dev"
-container="web"
+abort() {
+  printf "%s\n" "$@" >&2
+  exit 1
+}
 
+# Fail fast if not on Linux or Mac
+OS="$(uname)"
+if [[ "${OS}" == "Linux" ]]
+then
+  LINUX=1
+elif [[ "${OS}" == "Darwin" ]]
+then
+  MACOS=1
+else
+  abort "Terrastories is only supported on macOS and Linux."
+fi
+
+# Fail fast if no internet cnonection is detected
+ping -q -c1 google.com &>/dev/null && true || abort "Internet connection is required to complete setup."
+
+## Fail Fast if previous setup is detected
+shouldRun=false
+
+if [ ! -f .env ]; then
+  shouldRun=true
+else
+  echo "Oops. It looks like you've already setup Terrastories."
+  echo "You can re-run setup, or run bin/update to update your instance."
+  echo
+  read -p "Are you sure you want to re-reun setup? (y/n) " rerun
+
+  if [ "$rerun" = "Y" ] || [ "$rerun" = "y" ]; then
+    shouldRun=true
+  fi
+fi
+
+if ! $shouldRun; then
+  exit 0
+fi
+
+# Set Colors & Bold
+Blue='\033[0;36m'
 Green='\033[0;32m'
 Purple='\033[0;35m'
-BoldGreen='\033[1;32m'
-BoldPurple='\033[1;35m'
-ColorOff='\033[00m'
+Off='\033[00m'
+Bold='\033[1m'
 
-echo -e "${BoldPurple}Configure for Offline Field Kit${ColorOff}"
+## Start Helpers
+shell_join() {
+  local arg
+  printf "%s" "$1"
+  shift
+  for arg in "$@"
+  do
+    printf " "
+    printf "%s" "${arg// /\ }"
+  done
+}
 
-echo
-echo "Field Kit mode runs 'offline' or disconnected from the internet."
-echo
+ohai() {
+  printf "${Purple}==>${Bold} %s${Off}\n" "$(shell_join "$@")"
+}
 
-read -p "Setup for offline 'Field Kit' mode? [y/n] " offline
-
-if [ "$offline" = "y" ] || [ "$offline" = "Y" ]; then
-  container="localweb"
-  profile="offline"
-
-  if [ ! -f tileserver/data/styles/style.json ]; then
-    echo
-    echo -e "${Purple}==> Configure Local Tileserver${ColorOff}"
-    echo "A local Tileserver is required to run offline. You can use the"
-    echo "Terrastories default offline map tiles, or you can generate your own."
-    echo
-
-    read -p "Use default offline map tiles? This will overwrite any files already in tileserver/data [y/n] " default
-    if [ "$default" = "y" ] || [ "$default" = "Y" ]; then
-      echo
-      printf "Downloading and configuring default offline tiles..."
-      if [ ! -f tmp ]; then
-        git clone --quiet "https://github.com/Terrastories/default-offline-map/" tmp
-      fi
-      cp -r tmp/fonts/* tileserver/data/fonts
-      cp tmp/sprites/* tileserver/data/sprites
-      cp tmp/styles/* tileserver/data/styles
-      rm -rf tmp
-      curl -fsSL "https://bit.ly/39EdYoQ" -o "tileserver/data/mbtiles/tiles.mbtiles" --create-dirs
-      echo -e "...${Green}done!${ColorOff}"
-    fi
+execute() {
+  if ! "$@"
+  then
+    abort "$(printf "Failed during: %s" "$(shell_join "$@")")"
   fi
+}
+## End Helpers
 
-  if ! grep -q "terrastories.local" /etc/hosts; then
-    echo
-    echo -e "${Purple}==> Configure terrastories.local Domain${ColorOff}"
-    echo "By default, offline Terrastories field kit is accessible via localhost"
-    echo "or a local IP on the host machine. To faciliate easier access, you can"
-    echo "configure our custom terrastories.local domain to access Terrastories."
-    echo
-    echo "This can be done manually by editing your /etc/hosts file, or you can"
-    echo "provide your password when prompted to automatically configure them."
-    echo
-    echo "Choose one:"
-    echo "  (1) Manual"
-    echo "  (2) Automatic"
-    echo "  (3) Skip configuration"
-    echo
-    read -p "Your choice: " choice
+# Set Up Start
+ohai "Configure Network Access"
+read -p "$(
+  cat <<NETWORK
 
-    if [ $choice -eq 2 ]; then
-      echo
-      printf "Automatically configuring terrastories.local..."
-      sudo -- sh -c "echo '# Added by Terrastories\n127.0.0.1 terrastories.local\n# End of section' >> /etc/hosts"
-      echo -e "...${Green}done!${ColorOff}"
-    elif [ $choice -eq 1 ]; then
-      echo
-      echo "In a new terminal, open /etc/hosts with appropriate write permissions"
-      echo "and add the following line:"
-      echo
-      echo "  127.0.0.1 terrastories.local"
-      echo
-      read -p "Please go make those changes now. Press any key to continue or q to quit. " -n 1 k
+Would you like to enable network access?
+
+    (1) Yes, I would like to enable network access
+    (2) No, I only plan on using my machine [default]
+
+Your choice: 
+NETWORK
+  )" addhosts
+
+hostname=$(hostname)
+if [ $addhosts -eq 2 ]; then
+  unset hostname
+else
+  echo
+  read -p "Specify hostname: [$hostname] " hosts
+  hostname=${hosts:-$hostname}
+
+  if [ "$hostname" == "$(hostname)" ]; then
+    echo "You have specified your own hostname, no further configuration needed."
+  elif ! grep -q "$hostname" /etc/hosts; then
+    ohai Configure Host Domain
+    read -p "$(
+      cat <<MODHOSTS
+
+In order to utilize $hostname, you must add it to your /etc/hosts file.
+This can be done manually by editing your /etc/hosts file, or you can provide your
+password when prompted to allow us to automatically configure them.
+
+  Choose one:
+    (1) Manual
+    (2) Automatic
+
+Your choice: 
+MODHOSTS
+    )" modHosts
+
+    if [ $modHosts -eq 1 ]; then
+      read -p "$(
+cat <<HOSTS
+
+In a new terminal window, open /etc/hosts with appropriate write permissions
+and add the following line:
+
+  127.0.0.1 $hostname
+
+Press any key to continue or q to quit. 
+HOSTS
+      )" -n 1 k
       if [[ "$k" = "q" ]]; then
-        echo
-        echo "Quitting..."
         exit
       fi
     else
-      echo
-      echo "Skipping configuration"
+      echo "Automatically configuring terrastories.local. You may prompted for your password."
+      sudo -- sh -c "echo '# Added by Terrastories\n127.0.0.1 $hostname\n127.0.0.1 terrastories.local\n# End of section' >> /etc/hosts"
+      echo -e "...${Green}done!${Off}"
     fi
   fi
 fi
@@ -91,79 +140,51 @@ fi
 if [ ! -f .env ]; then
   cp .env.example .env
 fi
+if [ ! -f .env.api ]; then
+  cp .env.api.example .env.api
+fi
 
-# Local network access
-hostname=$(hostname)
-echo
-echo -e "${BoldPurple}Configure Network Access${ColorOff}"
-echo "By default, Terrastories can only be accessed by the machine hosting Terrastories."
-echo
-echo "Local Network Access is available for machines on the same network as the"
-echo "host machine using your host machine's hostname: $hostname."
-echo
-echo "Broader Network Access is available if you are familiar with networking"
-echo "or reverse proxying services such as ngrok, localtunnel, serveo, etc."
-echo
-echo "Would you like to enable network access?"
-echo "  (1) Yes, local network access using my hostname: $hostname"
-echo "  (2) Yes, broader network access using a custom hostname"
-echo "  (3) No, I only plan on using my machine"
-echo
-read -p "Your choice: " addhosts
-if [ $addhosts -eq 1 ]; then
+# Enable HOST_HOSTNAME
+if [ ! -z ${hostname-} ]; then
+  echo "$hostname"
   grep -v "HOST_HOSTNAME" .env > .envnew; mv .envnew .env
   echo "HOST_HOSTNAME=$hostname" >> .env
-elif [ $addhosts -eq 2 ]; then
-  echo
-  read -p "Specify hostname: [$hostname] " hosts
-
-  grep -v "HOST_HOSTNAME" .env > .envnew; mv .envnew .env
-  echo "HOST_HOSTNAME=${hosts:-$hostname}" >> .env
-else
-  echo
-  echo "Network access is disabled."
 fi
 
-echo
-echo "You may manage your hostname at any time in your .env file."
-
-## init db
-docker compose run --rm db postgres --version
-
-## start db
-docker compose up -d db
-
-## build app
-docker compose --profile $profile build
-
-## setup database
-docker compose --profile $profile run --rm $container bin/rails db:migrate
-
-## Seed database with demo data
-if [[ "$profile" = "dev" ]]; then
-  docker compose --profile dev run --rm $container bin/rails db:seed
+# Download default .pmtiles
+if [ ! -f map/terrastories-default/tiles.pmtiles ]; then
+  git clone --quiet "https://github.com/Terrastories/default-offline-map/" map/terrastories-default
+  curl -fsSL "https://bit.ly/45LGigh" -o "map/terrastories-default/tiles.pmtiles" --create-dirs
 fi
 
-## Precompile assets for offline mode
-if [[ "$profile" = "offline" ]]; then
-  docker compose --profile offline run --rm -e RAILS_ENV=offline $container bin/rails assets:precompile
-fi
+# Run Setup
+ohai Getting the latest Terrastories image
+docker compose up -d
 
-## run yarn
-docker compose --profile $profile run --rm $container yarn
+ohai Installing Dependencies
+docker compose exec web bundle check || bundle install
+docker compose exec web yarn
 
-echo
-echo -e "${BoldGreen}Welcome to Terrastories!$ColorOff"
-echo
+ohai Setting up your database
+docker compose exec web bin/rails db:prepare
 
-if [[ "$profile" = "dev" ]]; then
-  echo "!! Note: Terrastories requires a Mapbox Access Token for the mapping capabilities to work."
-  echo "         Please update the \`.env\` file with a valid Mapbox access token or configure one"
-  echo "         in your Community's Theme settings."
-  echo "         Ask a Terrastories steward for help if you are unsure or need one provided."
-  echo
-fi
-echo "Boot up your Terrastories instance with the following command:"
-echo
-echo "  docker compose --profile $profile up"
-echo
+ohai Finishing up…
+docker compose stop
+
+echo -e "${Blue}$(
+  cat <<TERRASTORIES_ASCII
+_ _ _ ____ _    ____ ____ _  _ ____    ___ ____
+| | | |___ |    |    |  | |\/| |___     |  |  |
+|_|_| |___ |___ |___ |__| |  | |___     |  |__|
+ _______ _______ ______   ______   _______ _______ _______ _______ ______   ___ _______ _______
+|       |       |    _ | |    _ | |   _   |       |       |       |    _ | |   |       |       |
+|_     _|    ___|   | || |   | || |  |_|  |  _____|_     _|   _   |   | || |   |    ___|  _____|
+  |   | |   |___|   |_||_|   |_||_|       | |_____  |   | |  | |  |   |_||_|   |   |___| |_____
+  |   | |    ___|    __  |    __  |       |_____  | |   | |  |_|  |    __  |   |    ___|_____  |
+  |   | |   |___|   |  | |   |  | |   _   |_____| | |   | |       |   |  | |   |   |___ _____| |
+  |___| |_______|___|  |_|___|  |_|__| |__|_______| |___| |_______|___|  |_|___|_______|_______|
+TERRASTORIES_ASCII
+  )${Off}"
+
+ohai "Boot up your Terrastories instance with the following command:"
+echo "  docker compose up"
